# - Configuration file stored 2023-09-25 12:30:42.164969 - 
LaserConfig: #!!python/object:controller.LaserConfig
 wavelength_range: 850 # wavelength_range: None
 velocity: 2.0 # velocity: None
 acceleration: 1.0 # acceleration: None
 deceleration: 1.0 # deceleration: None
 port: "USB 0" # port: None
