# - Configuration file stored 2023-09-26 14:00:16.732325 - 
ApplicationConfig: #!!python/object:controller.ApplicationConfig
 output_directory: "@Path:<C:/{wafer_nr}>" # Output Directory: The version of the wafer
 wafer_version: "v1.0" # wafer_version: The version of the wafer
 wafer_number: 1 # wafer_number: The version of the wafer
 wafer_nr: "12345ABCD_{wafer_number}" # wafer_nr: The version of the wafer
 wafer_number2: (1, 2) # wafer_number2: The version of the wafer
 wafer_list: [1, 2] # wafer_list: The version of the wafer

# Sub-Configurations
 laser_config: #!!python/object:controller.LaserConfig
   wavelength_range: 850 # wavelength_range: None
   velocity: 2.0 # velocity: None
   acceleration: 1.0 # acceleration: None
   deceleration: 1.0 # deceleration: None
   port: "USB 0" # port: None

